In [1]:
import pandas as pd

In [30]:
dd=pd.read_csv("datasets/daraz_dataset.csv")
# print(dd)
# print(dd.shape)
# print(dd.columns)
# print(dd.info())
# print(dd["TotalAmount"].max())
# print(dd["TotalAmount"].min())
# print(dd["TotalAmount"].mean())
# print(dd[["CustomerName","District","TotalAmount"]])
# print(dd.head(1))
# print(dd.iloc[11])#11 index ko row lai tanyo
# print(dd.iloc[0:11])#0 to 11-1=10 index ko row lai tanyo
# print(dd.iloc[0,2])#0 row ko 2nd index lai samatyo which is customer name
# print(dd.iloc[:,2])#every row ko 2nd index lai samatyo which is customer name
# print(dd.iloc[:,[2,6]])#every row ko mention gareko column side ko index lai samatcha
# print(dd.iloc[-1]#last row dekhaucha
# print(dd.iloc[1:5,1:7])
# print(dd.loc[:,"CustomerName"])#loc displays rows according to name or string of column
# print(dd.loc[:,["CustomerName","District"]])
# print(dd.loc[dd["District"]=="Kathmandu"])
# print(dd.loc[dd["TotalAmount"]>30000])
# print(dd.loc[(dd["District"]=="Kathmandu") & (dd["PaymentMethod"]=="eSewa")])
# print(dd.loc[(dd["Category"]=="Electronics") & (dd["Rating"]==5)])
# print(dd.loc[(dd["Category"]=="Electronics") & (dd["Rating"]==5)])
# print(dd.sort_values("TotalAmount"))#by default on ascending from cheaper to expensive or low to high
# print(dd.sort_values("TotalAmount",ascending=False)) #sorts on descending order from high to low

In [33]:
bdd=pd.read_csv("datasets/bad_daraz_dataset.csv")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [52]:
# bdd.isnull()#catches nan values datatypes 
# # bdd.isnull().sum()#catches nan values datatypes and sum
# bdd.fillna(0)#fills nan value or missing value with 0
# bdd["price"]=pd.to_numeric(bdd["price"],errors="coerce")
# bdd
bdd["price"]=bdd["price"].fillna(bdd["price"].mean())#fills nan value or missing value with mean
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [35]:
bdd["age"]=pd.to_numeric(bdd["age"],errors="coerce")
bdd["age"]=bdd["age"].fillna(bdd["age"].median())
bdd["age"]

0     25.0
1     30.0
2     22.0
3     25.0
4     28.0
5     24.0
6     25.0
7     19.0
8     25.0
9     21.0
10    26.0
11    25.0
12    25.0
Name: age, dtype: float64

In [66]:
# bdd.dropna()#drops the row where any value is na or null or Nan
# bdd[bdd.duplicated()]
# bdd["discount_percent"]=bdd["discount_percent"].str.replace("%","")
# bdd["discount_percent"]=pd.to_numeric(bdd["discount_percent"],errors="coerce")
# bdd["discount_percent"]
# bdd["discount_percent"]=bdd["discount_percent"].fillna(bdd["discount_percent"].mean())
# bdd["discount_percent"].fillna(bdd["discount_percent"].mean())
# bdd["discount_percent"]
# bdd.drop_duplicates()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15.000000,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5.000000,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10.000000,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12.000000,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.000000,5.000000,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0.000000,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10.000000,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10.000000,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44