In [3]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

In [4]:
df = pd.read_csv(
    "datasets/student_multiclass_multiple_features.csv"
)

print("Dataset:")
display(df)



X = df[
    [
        "Attendance",
        "PreviousMarks",
        "StudyHours"
    ]
]

y = df["Result"]


print("\nFeatures (X):")
display(X)

print("\nTarget (y):")
display(y)




X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


print("\nTraining data:", X_train.shape)
print("Testing data :", X_test.shape)


scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)




knn = KNeighborsClassifier(
    n_neighbors=3
)



knn.fit(
    X_train_scaled,
    y_train
)


y_pred = knn.predict(
    X_test_scaled
)


print("\nActual values:")
print(y_test.values)

print("\nPredicted values:")
print(y_pred)


accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)


print("\n==============================")
print("MODEL PERFORMANCE")
print("==============================")

print("Accuracy :", round(accuracy, 3))
print("Precision:", round(precision, 3))
print("Recall   :", round(recall, 3))
print("F1-score :", round(f1, 3))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)


new_student = pd.DataFrame({
    "Attendance": [85],
    "PreviousMarks": [65],
    "StudyHours": [5.5]
})



new_student_scaled = scaler.transform(
    new_student
)



new_prediction = knn.predict(
    new_student_scaled
)[0]


print("\n==============================")
print("NEW STUDENT PREDICTION")
print("==============================")

print("Attendance   :", new_student["Attendance"].iloc[0])
print("PreviousMarks:", new_student["PreviousMarks"].iloc[0])
print("StudyHours   :", new_student["StudyHours"].iloc[0])

print("\nPredicted Result:", new_prediction)



distances, indices = knn.kneighbors(
    new_student_scaled,
    n_neighbors=3
)


print("\n==============================")
print("3 NEAREST STUDENTS")
print("==============================")


train_indices = X_train.index.tolist()


for i in range(3):

    position = indices[0][i]

    original_index = train_indices[position]

    student = df.loc[original_index]

    print(f"\n{i + 1}. {student['Student']}")

    print("   Study Hours   :", student["StudyHours"])

    print("   Attendance    :", student["Attendance"])

    print("   Previous Marks:", student["PreviousMarks"])

    print("   Result        :", student["Result"])

    print("   Distance      :", round(distances[0][i], 3))

Dataset:

    Student  StudyHours  Attendance  PreviousMarks   Result
0     Aarav           1          55             28     Fail
1      Sita           2          60             32     Fail
2       Ram           2          65             36     Fail
3    Anisha           3          70             40     Fail
4     Rohan           3          72             43     Fail
5     Priya           4          75             48  Average
6     Kiran           4          78             52  Average
7     Nabin           5          80             56  Average
8     Suman           5          82             60  Average
9    Alisha           5          84             63  Average
10   Bikash           6          86             67     Good
11   Sabina           6          88             70     Good
12   Roshan           6          90             73     Good
13     Puja           7          91             76     Good
14   Manish           7          92             79     Good
15     Rita           7          93             82     Good
16    Deepa           8          94             84     Good
17   Sanjay           8          95             87     Good
18   Kushal           8          96             89     Good
19   Aakash           9          97             91     Good
20     Bina           9          90             75     Good
21  Nischal           9          94             85     Good
22    Rekha          10          98             93     Good
23    Sagar          10          99             95     Good
24     Mina          10          96             90     Good

Features (X):

    Attendance  PreviousMarks  StudyHours
0           55             28           1
1           60             32           2
2           65             36           2
3           70             40           3
4           72             43           3
5           75             48           4
6           78             52           4
7           80             56           5
8           82             60           5
9           84             63           5
10          86             67           6
11          88             70           6
12          90             73           6
13          91             76           7
14          92             79           7
15          93             82           7
16          94             84           8
17          95             87           8
18          96             89           8
19          97             91           9
20          90             75           9
21          94             85           9
22          98             93          10
23          99             95          10
24          96             90          10

Target (y):

0        Fail
1        Fail
2        Fail
3        Fail
4        Fail
5     Average
6     Average
7     Average
8     Average
9     Average
10       Good
11       Good
12       Good
13       Good
14       Good
15       Good
16       Good
17       Good
18       Good
19       Good
20       Good
21       Good
22       Good
23       Good
24       Good
Name: Result, dtype: str

Training data: (20, 3)
Testing data : (5, 3)

Actual values:
<StringArray>
['Good', 'Good', 'Fail', 'Good', 'Average']
Length: 5, dtype: str

Predicted values:
['Good' 'Good' 'Average' 'Good' 'Average']

==============================
MODEL PERFORMANCE
==============================
Accuracy : 0.8
Precision: 0.7
Recall   : 0.8
F1-score : 0.733

Classification Report:
              precision    recall  f1-score   support

     Average       0.50      1.00      0.67         1
        Fail       0.00      0.00      0.00         1
        Good       1.00      1.00      1.00         3

    accuracy                           0.80         5
   macro avg       0.50      0.67      0.56         5
weighted avg       0.70      0.80      0.73         5


==============================
NEW STUDENT PREDICTION
==============================
Attendance   : 85
PreviousMarks: 65
StudyHours   : 5.5

Predicted Result: Good

==============================
3 NEAREST STUDENTS
==============================

1. Bikash
   Study Hours   : 6
   Attendance    : 86
   Previous Marks: 67
   Result        : Good
   Distance      : 0.217

2. Alisha
   Study Hours   : 5
   Attendance    : 84
   Previous Marks: 63
   Result        : Average
   Distance      : 0.217

3. Sabina
   Study Hours   : 6
   Attendance    : 88
   Previous Marks: 70
   Result        : Good
   Distance      : 0.373